# CI Test - Build the action container
# build test container which has default test files and validate
name: CRDA scan Node Example
on: [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Analyse Node project
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install

      - name: Install CRDA
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          github_pat: ${{ github.token }}
          crda: "latest"

      - name: CRDA Scan
        id: scan
        uses: divyansh42/crda-action@main
        with:
          manifest_file_path: package.json
          # crda_key: ${{ secrets.CRDA_KEY }}
          snyk_token: ${{ secrets.SNYK_TOKEN }}
          analysis_report_file_name: node
          consent_telemetry: true

      - name: Print Analysis Report
        if: always()
        run: cat ${{ steps.scan.outputs.crda_report_json }}

      - name: Print Sarif
        if: always()
        run: cat ${{ steps.scan.outputs.crda_report_sarif }}

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.crda_report_sarif }}

      - name: Save intermediate files
        run: |
          mkdir -p uploads
          mv ${{ steps.scan.outputs.crda_report_json }} uploads
          mv ${{ steps.scan.outputs.crda_report_sarif }} uploads

      - name: Upload merged Results
        uses: actions/upload-artifact@v2
        with:
          name: workfiles_node
          path: ./uploads
